services:
  app:
    container_name: app
    build:
      context: .
    command: "sleep infinity"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    networks:
      - dev-net
    env_file:
      - .env.development
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:6
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env.development
    volumes:
      - mongo_data:/data/db
    networks:
      - dev-net

  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    env_file:
      - .env.development
    volumes:
      - redis-stack-data:/data
    networks:
      - dev-net

volumes:
  app:
  mongo_data:
  redis-stack-data:

networks:
  dev-net: